class Mdata():
    """ Container holding static data """

    availability = {
        'payload_available': False,
        'payload_not_available': True,
        'value_template': '{{ value_json.v|bool }}'
    }
    cTemplate = '{"v": {{ value }} }'
    cTemplatePrg = '{"v": true}'
    diag = ('BATTERY_STATE',
            'BURST_LIMIT_WARNING',
            'CONFIG_PENDING',
            'DUTY_CYCLE',
            'ERROR_DEGRADED_CHAMBER',
            'LEVEL', 'LOW_BAT',
            'OPERATING_VOLTAGE',
            'RSSI_DEVICE', 'RSSI_PEER',
            'SMOKE_DETECTOR_ALARM_STATUS',
            'SMOKE_DETECTOR_TEST_RESULT',
            'TIME_OF_OPERATION')
    jTemplateTs = '{% set ts=value_json.ts|int %}{{ {"lang15": iif(' + \
                  'ts==0, "lang16", (ts/1000)|timestamp_local(), "n' + \
                  '/a")}|to_json() }}'
    lang = {
        'lang0': ('off', 'ein'),
        'lang1': ('primary', 'primär'),
        'lang2': ('intrusion', 'Eindringling'),
        'lang3': ('secondary', 'sekundär'),
        'lang4': ('alarm', 'Alarm'),
        'lang5': ('n/a', 'n/a'),
        'lang6': ('smoke test ok', 'Rauchtest ok'),
        'lang7': ('smoke test fail', 'Rauchtestfehler'),
        'lang8': ('connection test started', 'Verbindungstest gestartet'),
        'lang9': ('connection test ok', 'Verbindungstest ok'),
        'lang10': ('days', 'Tage'),
        'lang11': ('no', 'nein'),
        'lang12': ('yes', 'ja'),
        'lang13': ('System Variables', 'Systemvariablen'),
        'lang14': ('Programs', 'Programme'),
        'lang15': ('Last run', 'Zuletzt ausgeführt'),
        'lang16': ('never', 'nie')
    }
    langTr = [
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [10],
        [11, 12],
        [13],
        [14],
        [15, 16]
    ]
    mqttAbbr = {
        'action_template': 'act_tpl',
        'action_topic': 'act_t',
        'automation_type': 'atype',
        'aux_command_topic': 'aux_cmd_t',
        'aux_state_template': 'aux_stat_tpl',
        'aux_state_topic': 'aux_stat_t',
        'availability': 'avty',
        'availability_mode': 'avty_mode',
        'availability_template': 'avty_tpl',
        'availability_topic': 'avty_t',
        'available_tones': 'av_tones',
        'away_mode_command_topic': 'away_mode_cmd_t',
        'away_mode_state_template': 'away_mode_stat_tpl',
        'away_mode_state_topic': 'away_mode_stat_t',
        'battery_level_template': 'bat_lev_tpl',
        'battery_level_topic': 'bat_lev_t',
        'blue_template': 'b_tpl',
        'brightness_command_template': 'bri_cmd_tpl',
        'brightness_command_topic': 'bri_cmd_t',
        'brightness_scale': 'bri_scl',
        'brightness_state_topic': 'bri_stat_t',
        'brightness_template': 'bri_tpl',
        'brightness_value_template': 'bri_val_tpl',
        'charging_template': 'chrg_tpl',
        'charging_topic': 'chrg_t',
        'cleaning_template': 'cln_tpl',
        'cleaning_topic': 'cln_t',
        'code_arm_required': 'cod_arm_req',
        'code_disarm_required': 'cod_dis_req',
        'code_trigger_required': 'cod_trig_req',
        'color_mode': 'clrm',
        'color_mode_state_topic': 'clrm_stat_t',
        'color_mode_value_template': 'clrm_val_tpl',
        'color_temp_command_template': 'clr_temp_cmd_tpl',
        'color_temp_command_topic': 'clr_temp_cmd_t',
        'color_temp_state_topic': 'clr_temp_stat_t',
        'color_temp_template': 'clr_temp_tpl',
        'color_temp_value_template': 'clr_temp_val_tpl',
        'command_off_template': 'cmd_off_tpl',
        'command_on_template': 'cmd_on_tpl',
        'command_template': 'cmd_tpl',
        'command_topic': 'cmd_t',
        'configuration_url': 'cu',
        'connections': 'cns',
        'content_type': 'cont_type',
        'current_temperature_template': 'curr_temp_tpl',
        'current_temperature_topic': 'curr_temp_t',
        'device': 'dev',
        'device_class': 'dev_cla',
        'direction_command_template': 'dir_cmd_tpl',
        'direction_command_topic': 'dir_cmd_t',
        'direction_state_topic': 'dir_stat_t',
        'direction_value_template': 'dir_val_tpl',
        'docked_template': 'dock_tpl',
        'docked_topic': 'dock_t',
        'effect_command_template': 'fx_cmd_tpl',
        'effect_command_topic': 'fx_cmd_t',
        'effect_list': 'fx_list',
        'effect_state_topic': 'fx_stat_t',
        'effect_template': 'fx_tpl',
        'effect_value_template': 'fx_val_tpl',
        'enabled_by_default': 'en',
        'encoding': 'e',
        'entity_category': 'ent_cat',
        'entity_picture': 'ent_pic',
        'error_template': 'err_tpl',
        'error_topic': 'err_t',
        'event_types': 'evt_typ',
        'expire_after': 'exp_aft',
        'fan_mode_command_template': 'fan_mode_cmd_tpl',
        'fan_mode_command_topic': 'fan_mode_cmd_t',
        'fan_mode_state_template': 'fan_mode_stat_tpl',
        'fan_mode_state_topic': 'fan_mode_stat_t',
        'fan_speed_list': 'fanspd_lst',
        'fan_speed_template': 'fanspd_tpl',
        'fan_speed_topic': 'fanspd_t',
        'flash_time_long': 'flsh_tlng',
        'flash_time_short': 'flsh_tsht',
        'force_update': 'frc_upd',
        'green_template': 'g_tpl',
        'hs_command_template': 'hs_cmd_tpl',
        'hs_command_topic': 'hs_cmd_t',
        'hs_state_topic': 'hs_stat_t',
        'hs_value_template': 'hs_val_tpl',
        'hw_version': 'hw',
        'icon': 'ic',
        'identifiers': 'ids',
        'image_encoding': 'img_e',
        'image_topic': 'img_t',
        'initial': 'init',
        'json_attributes': 'json_attr',
        'json_attributes_template': 'json_attr_tpl',
        'json_attributes_topic': 'json_attr_t',
        'last_reset_topic': 'lrst_t',
        'last_reset_value_template': 'lrst_val_tpl',
        'latest_version_template': 'l_ver_tpl',
        'latest_version_topic': 'l_ver_t',
        'manufacturer': 'mf',
        'max': 'max',
        'max_humidity': 'max_hum',
        'max_mireds': 'max_mirs',
        'max_temp': 'max_temp',
        'min': 'min',
        'min_humidity': 'min_hum',
        'min_mireds': 'min_mirs',
        'min_temp': 'min_temp',
        'mode': 'mode',
        'mode_command_template': 'mode_cmd_tpl',
        'mode_command_topic': 'mode_cmd_t',
        'mode_state_template': 'mode_stat_tpl',
        'mode_state_topic': 'mode_stat_t',
        'model': 'mdl',
        'modes': 'modes',
        'name': 'name',
        'object_id': 'obj_id',
        'off_delay': 'off_dly',
        'on_command_type': 'on_cmd_type',
        'optimistic': 'opt',
        'options': 'ops',
        'origin': 'o',
        'oscillation_command_template': 'osc_cmd_tpl',
        'oscillation_command_topic': 'osc_cmd_t',
        'oscillation_state_topic': 'osc_stat_t',
        'oscillation_value_template': 'osc_val_tpl',
        'pattern': 'ptrn',
        'payload': 'pl',
        'payload_arm_away': 'pl_arm_away',
        'payload_arm_custom_bypass': 'pl_arm_custom_b',
        'payload_arm_home': 'pl_arm_home',
        'payload_arm_night': 'pl_arm_nite',
        'payload_arm_vacation': 'pl_arm_vacation',
        'payload_available': 'pl_avail',
        'payload_clean_spot': 'pl_cln_sp',
        'payload_close': 'pl_cls',
        'payload_direction_forward': 'pl_dir_fwd',
        'payload_direction_reverse': 'pl_dir_rev',
        'payload_disarm': 'pl_disarm',
        'payload_home': 'pl_home',
        'payload_install': 'pl_inst',
        'payload_locate': 'pl_loc',
        'payload_lock': 'pl_lock',
        'payload_not_available': 'pl_not_avail',
        'payload_not_home': 'pl_not_home',
        'payload_off': 'pl_off',
        'payload_on': 'pl_on',
        'payload_open': 'pl_open',
        'payload_oscillation_off': 'pl_osc_off',
        'payload_oscillation_on': 'pl_osc_on',
        'payload_pause': 'pl_paus',
        'payload_press': 'pl_prs',
        'payload_reset': 'pl_rst',
        'payload_reset_humidity': 'pl_rst_hum',
        'payload_reset_mode': 'pl_rst_mode',
        'payload_reset_percentage': 'pl_rst_pct',
        'payload_reset_preset_mode': 'pl_rst_pr_mode',
        'payload_return_to_base': 'pl_ret',
        'payload_start': 'pl_strt',
        'payload_start_pause': 'pl_stpa',
        'payload_stop': 'pl_stop',
        'payload_trigger': 'pl_trig',
        'payload_turn_off': 'pl_toff',
        'payload_turn_on': 'pl_ton',
        'payload_unlock': 'pl_unlk',
        'percentage_command_template': 'pct_cmd_tpl',
        'percentage_command_topic': 'pct_cmd_t',
        'percentage_state_topic': 'pct_stat_t',
        'percentage_value_template': 'pct_val_tpl',
        'position_closed': 'pos_clsd',
        'position_open': 'pos_open',
        'position_template': 'pos_tpl',
        'position_topic': 'pos_t',
        'preset_mode_command_template': 'pr_mode_cmd_tpl',
        'preset_mode_command_topic': 'pr_mode_cmd_t',
        'preset_mode_state_topic': 'pr_mode_stat_t',
        'preset_mode_value_template': 'pr_mode_val_tpl',
        'preset_modes': 'pr_modes',
        'red_template': 'r_tpl',
        'release_summary': 'rel_s',
        'release_url': 'rel_u',
        'retain': 'ret',
        'rgb_command_template': 'rgb_cmd_tpl',
        'rgb_command_topic': 'rgb_cmd_t',
        'rgb_state_topic': 'rgb_stat_t',
        'rgb_value_template': 'rgb_val_tpl',
        'rgbw_command_template': 'rgbw_cmd_tpl',
        'rgbw_command_topic': 'rgbw_cmd_t',
        'rgbw_state_topic': 'rgbw_stat_t',
        'rgbw_value_template': 'rgbw_val_tpl',
        'rgbww_command_template': 'rgbww_cmd_tpl',
        'rgbww_command_topic': 'rgbww_cmd_t',
        'rgbww_state_topic': 'rgbww_stat_t',
        'rgbww_value_template': 'rgbww_val_tpl',
        'send_command_topic': 'send_cmd_t',
        'send_if_off': 'send_if_off',
        'set_fan_speed_topic': 'set_fan_spd_t',
        'set_position_template': 'set_pos_tpl',
        'set_position_topic': 'set_pos_t',
        'source_type': 'src_type',
        'speed_range_max': 'spd_rng_max',
        'speed_range_min': 'spd_rng_min',
        'state_class': 'stat_cla',
        'state_closed': 'stat_clsd',
        'state_closing': 'stat_closing',
        'state_jammed': 'stat_jam',
        'state_locked': 'stat_locked',
        'state_locking': 'stat_locking',
        'state_off': 'stat_off',
        'state_on': 'stat_on',
        'state_open': 'stat_open',
        'state_opening': 'stat_opening',
        'state_stopped': 'stat_stopped',
        'state_template': 'stat_tpl',
        'state_topic': 'stat_t',
        'state_unlocked': 'stat_unlocked',
        'state_unlocking': 'stat_unlocking',
        'state_value_template': 'stat_val_tpl',
        'step': 'step',
        'subtype': 'stype',
        'suggested_area': 'sa',
        'suggested_display_precision': 'sug_dsp_prc',
        'support_duration': 'sup_dur',
        'support_url': 'url',
        'support_volume_set': 'sup_vol',
        'supported_color_modes': 'sup_clrm',
        'supported_features': 'sup_feat',
        'sw_version': 'sw',
        'swing_mode_command_template': 'swing_mode_cmd_tpl',
        'swing_mode_command_topic': 'swing_mode_cmd_t',
        'swing_mode_state_template': 'swing_mode_stat_tpl',
        'swing_mode_state_topic': 'swing_mode_stat_t',
        'target_humidity_command_template': 'hum_cmd_tpl',
        'target_humidity_command_topic': 'hum_cmd_t',
        'target_humidity_state_template': 'hum_state_tpl',
        'target_humidity_state_topic': 'hum_stat_t',
        'temperature_command_template': 'temp_cmd_tpl',
        'temperature_command_topic': 'temp_cmd_t',
        'temperature_high_command_template': 'temp_hi_cmd_tpl',
        'temperature_high_command_topic': 'temp_hi_cmd_t',
        'temperature_high_state_template': 'temp_hi_stat_tpl',
        'temperature_high_state_topic': 'temp_hi_stat_t',
        'temperature_low_command_template': 'temp_lo_cmd_tpl',
        'temperature_low_command_topic': 'temp_lo_cmd_t',
        'temperature_low_state_template': 'temp_lo_stat_tpl',
        'temperature_low_state_topic': 'temp_lo_stat_t',
        'temperature_state_template': 'temp_stat_tpl',
        'temperature_state_topic': 'temp_stat_t',
        'temperature_unit': 'temp_unit',
        'tilt_closed_value': 'tilt_clsd_val',
        'tilt_command_template': 'tilt_cmd_tpl',
        'tilt_command_topic': 'tilt_cmd_t',
        'tilt_max': 'tilt_max',
        'tilt_min': 'tilt_min',
        'tilt_opened_value': 'tilt_opnd_val',
        'tilt_optimistic': 'tilt_opt',
        'tilt_status_template': 'tilt_status_tpl',
        'tilt_status_topic': 'tilt_status_t',
        'title': 'tit',
        'topic': 't',
        'unique_id': 'uniq_id',
        'unit_of_measurement': 'unit_of_meas',
        'url_template': 'url_tpl',
        'url_topic': 'url_t',
        'value_template': 'val_tpl',
        'white_command_topic': 'whit_cmd_t',
        'white_scale': 'whit_scl',
        'xy_command_template': 'xy_cmd_tpl',
        'xy_command_topic': 'xy_cmd_t',
        'xy_state_topic': 'xy_stat_t',
        'xy_value_template': 'xy_val_tpl'
    }
    origin = {
        'name': 'Jacking2Ha',
        'sw_version': '0.1.1',
        'support_url': 'https://github.com/elix-g/jacking2ha'
    }
    vTemplate = '{{ value_json.v }}'
    vTemplateBinary = '{{ value_json.v|bool }}'
    vTemplateLevel = '{{ value_json.v|float * 100 }}'
    vTemplateSdas = '{% set text = value_json.v|string|regex_replace(fin' + \
                    'd="0", replace="lang0")|regex_replace(find="1", rep' + \
                    'lace="lang1")|regex_replace(find="2", replace="lang' + \
                    '2")|regex_replace(find="3", replace="lang3") %}lang' + \
                    '4 {{ text }}'
    vTemplateSdtr = '{% set text = value_json.v|string|regex_replace(fin' + \
                    'd="0", replace="lang5")|regex_replace(find="1", rep' + \
                    'lace="lang6")|regex_replace(find="2", replace="lang' + \
                    '7")|regex_replace(find="3", replace="lang8")|regex_' + \
                    'replace(find="4", replace="lang9") %}{{ text }}'
    vTemplateToo = '{{ (value_json.v|int / 86400)|int }} lang10'
